blank_issues_enabled: true
contact_links:
  - name: Comcells Matrix Space
    url: https://app.element.io/#/room/%23comcellsui_space%3Amatrix.org
    about: The Comcells Matrix Space is available for support and general discussion related to Comcells (Matrix is like Discord but open source).
  - name: Comfy Org Discord
    url: https://discord.gg/comcellsorg
    about: The Comfy Org Discord is available for support and general discussion related to Comcells.
